version: '3.1'

services:
 
  weatherapp_backend:
    build: ./backend
    ports:
      - "9000:90"
    volumes:
     - backend:/app/backend


  weatherapp_front:
      build: ./frontend
      ports:
        - "8000:80"
      volumes:
       - frontend:/app/frontend
      environment: 
        NODE_ENV: "development"
      

volumes:
  backend:
  frontend:
   

  
  


