version: '3.1'

services:
 
  weatherapp_backend:
    build: ./backend
    ports:
      - "9000:9000"
    volumes:
     - backend:/app/backend


  weatherapp_front:
      build: ./frontend
      ports:
        - "8000:8000"
      volumes:
       - frontend:/app/frontend
      

volumes:
  backend:
  frontend:
   

  
  


